test_task_template: &TEST_TASK_TEMPLATE
  testset_script: |
    echo "testset-1"

task:
  name: ubuntu-aarch64
  arm_container:
# Needs ~10 Gb to package metanorma and Cirrus-ci allows 4GB per CPU only
    image: ubuntu:20.04
#    cpu: 3
#    memory: 12G

  env:
    CIRRUS_CLONE_SUBMODULES: true
    CIRRUS_CLONE_DEPTH: 1
    VERBOSE: yes
    CMAKE_VERSION: 3.20.5
    CC: clang
    CXX: clang++
# { CC: gcc, CXX: g++ } commented to save Cirrus-ci limited capacity
# (clang is better both for performance and size)

  install_script: |
    DEBIAN_FRONTEND=noninteractive apt-get -y update
    DEBIAN_FRONTEND=noninteractive \
    apt-get -y install sudo git curl build-essential pkg-config bison flex autoconf \
      binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev libiberty-dev    \
      libdouble-conversion-dev liblz4-dev liblzma-dev libssl-dev libunwind-dev      \
      libboost-context-dev libboost-filesystem-dev libboost-program-options-dev     \
      libboost-regex-dev libboost-system-dev libboost-thread-dev libdwarf-dev       \
      libelf-dev libfuse-dev libgoogle-glog-dev libffi-dev libgdbm-dev libyaml-dev  \
      libncurses-dev libreadline-dev clang ca-certificates

#ruby ruby-bundler
#sudo update-ca-certificates

#ruby ruby-bundler

  pre-setup_script: |
    git clone --depth 1 https://github.com/kward/shunit2.git tests/shunit2

  setup-cmake_script: |
    mkdir -p cmake-install
    pushd cmake-install
    curl --verbose -L -o cmake.sh \
    https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-aarch64.sh
    sudo sh cmake.sh --skip-license --prefix="/usr/local"
    popd

#    https://github.com/Kitware/CMake/releases/download/v"$CMAKE_VERSION"/cmake-"$CMAKE_VERSION"-linux-aarch64.sh


# cirrus-ci hash does not work for optimized Ruby patching/build
# most likely it changes file times that causes make do a kind of
# 'random' rebuild
#  setup_script: |
#    sudo gem install bundler
#    bundle install

  << : *TEST_TASK_TEMPLATE
