name: dependencies
on:
  workflow_dispatch:

jobs:
  dispatch-ruby-rnp:
    name: Dispatch Ryby-rnp repository
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token:  ${{ secrets.TEST_TOKEN_2 }}
          repository: 'rnpgp/ruby-rnp'
          event-type: run-ruby-rnp
          client-payload: '{ "tag": "master" }'
